# This is a basic workflow to help you get started with Actions

name: Monitor configuration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '*/5 * * * *'
  # push
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          repository: sassdawe/psconfeu-confmon-report
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: report
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: new branch
        run: |
          git config --global user.name 'David Sass'
          git config --global user.email 'sassdawe@users.noreply.github.com'
          git checkout -b report

      - name: Report on Function Apps
        uses: Azure/powershell@v1
        with:
          azPSVersion: "latest"
          # Specify the script here
          inlineScript: |
            & "$(Get-Location)/src/report-functionapp.ps1"
            & "$(Get-Location)/src/report-storageaccount.ps1"
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          #azcliversion: # optional, default is agentazcliversion
          
      - name: Commit report
        continue-on-error: true
        shell: pwsh
        run: |
          set-location ./report
          git add .
          git commit -am "Automated report"
          git push
          
          
