# This is a basic workflow to help you get started with Actions

name: Monitor configuration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: new branch
        run: |
          git config --global user.name 'David Sass'
          git config --global user.email 'sassdawe@users.noreply.github.com'
          git branch newbranch
          git checkout newbranch
          
      - name: Azure PowerShell actions with CLI
        uses: Azure/powershell@v1
        with:
          azPSVersion: "latest"
          # Specify the script here
          inlineScript:
            (az functionapp list | convertfrom-json | %{ $_ } ) | convertto-json | out-file .\functionapp-list.json;      
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          #azcliversion: # optional, default is agentazcliversion
          
      - name: Commit report
        run: |
          git commit -am "Automated report"
          git push origin newbranch
